name: Synchronize forked repositories

on:
  push:
  schedule:
# Every day at 05:50 (UTC+1) - rerun pipeline to check for updates on forked repositories
    - cron: '50 4 * * *'

jobs:
  Synchronize:
    runs-on: ubuntu-latest
    steps:
      - name: '🧰 Checkout'
        uses: actions/checkout@v6

      - name: Synchronize Repositories
        uses: pyTooling/SynchronizeForks@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
